### ISSUE TITLE
Crash "@adiwajshing/baileys"' has no exported member named 'MessageUpdateType'. Did you mean 'MessageUpsertType'?

### ISSUE THREAD

**Issue by joeBidenBalls** [Paiiss/bot-wa#14]
Hello, I am trying to deploy your bot to Heroku. I set up the MongoDB Atlas URL / Credentials correctly, everything should run fine except I get this error in heroku's console:

`'"@adiwajshing/baileys"' has no exported member named 'MessageUpdateType'. Did you mean 'MessageUpsertType'?`

Am I doing something wrong?

```
  2022-07-27T01:12:23.640671+00:00 app[web.1]: > bot-wa@2.6.9 server

2022-07-27T01:12:23.640672+00:00 app[web.1]: > ts-node --project ./tsconfig.json -r tsconfig-paths/register src/main.ts --server

2022-07-27T01:12:23.640672+00:00 app[web.1]: 

2022-07-27T01:12:29.964415+00:00 app[web.1]: /allen/node_modules/ts-node/src/index.ts:859

2022-07-27T01:12:29.964440+00:00 app[web.1]:     return new TSError(diagnosticText, diagnosticCodes, diagnostics);

2022-07-27T01:12:29.964440+00:00 app[web.1]:            ^

2022-07-27T01:12:29.966464+00:00 app[web.1]: TSError: ⨯ Unable to compile TypeScript:

2022-07-27T01:12:29.966470+00:00 app[web.1]: src/utils/connect.utils.ts(1,59): error TS2724: '"@adiwajshing/baileys"' has no exported member named 'MessageUpdateType'. Did you mean 'MessageUpsertType'?

2022-07-27T01:12:29.966471+00:00 app[web.1]: 

2022-07-27T01:12:29.966471+00:00 app[web.1]:     at createTSError (/allen/node_modules/ts-node/src/index.ts:859:12)

2022-07-27T01:12:29.966472+00:00 app[web.1]:     at reportTSError (/allen/node_modules/ts-node/src/index.ts:863:19)

2022-07-27T01:12:29.966472+00:00 app[web.1]:     at getOutput (/allen/node_modules/ts-node/src/index.ts:1077:36)

2022-07-27T01:12:29.966472+00:00 app[web.1]:     at Object.compile (/allen/node_modules/ts-node/src/index.ts:1433:41)

2022-07-27T01:12:29.966472+00:00 app[web.1]:     at Module.m._compile (/allen/node_modules/ts-node/src/index.ts:1617:30)

2022-07-27T01:12:29.966473+00:00 app[web.1]:     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)

2022-07-27T01:12:29.966474+00:00 app[web.1]:     at Object.require.extensions.<computed> [as .ts] (/allen/node_modules/ts-node/src/index.ts:1621:12)

2022-07-27T01:12:29.966474+00:00 app[web.1]:     at Module.load (node:internal/modules/cjs/loader:981:32)

2022-07-27T01:12:29.966475+00:00 app[web.1]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)

2022-07-27T01:12:29.966475+00:00 app[web.1]:     at Module.require (node:internal/modules/cjs/loader:1005:19) {

2022-07-27T01:12:29.966476+00:00 app[web.1]:   diagnosticCodes: [ 2724 ]

2022-07-27T01:12:29.966476+00:00 app[web.1]: }

2022-07-27T01:12:29.980965+00:00 app[web.1]: npm notice 

2022-07-27T01:12:29.981041+00:00 app[web.1]: npm notice New minor version of npm available! 8.11.0 -> 8.15.0

2022-07-27T01:12:29.981191+00:00 app[web.1]: npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.15.0>

2022-07-27T01:12:29.981235+00:00 app[web.1]: npm notice Run `npm install -g npm@8.15.0` to update!

2022-07-27T01:12:29.981359+00:00 app[web.1]: npm notice 

2022-07-27T01:12:30.111536+00:00 heroku[web.1]: Process exited with status 1

2022-07-27T01:12:30.221335+00:00 heroku[web.1]: State changed from starting to crashed
```

full log (it starts halfway an error for some reason)
```

2022-07-27T00:20:18.954692+00:00 app[web.1]:     at Module.require (node:internal/modules/cjs/loader:1005:19) {

2022-07-27T00:20:18.954692+00:00 app[web.1]:   diagnosticCodes: [ 2724 ]

2022-07-27T00:20:18.954693+00:00 app[web.1]: }

2022-07-27T00:20:18.969071+00:00 app[web.1]: npm notice 

2022-07-27T00:20:18.969153+00:00 app[web.1]: npm notice New minor version of npm available! 8.11.0 -> 8.15.0

2022-07-27T00:20:18.969300+00:00 app[web.1]: npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.15.0>

2022-07-27T00:20:18.969351+00:00 app[web.1]: npm notice Run `npm install -g npm@8.15.0` to update!

2022-07-27T00:20:18.969493+00:00 app[web.1]: npm notice 

2022-07-27T00:20:19.097712+00:00 heroku[web.1]: Process exited with status 1

2022-07-27T00:20:19.149436+00:00 heroku[web.1]: State changed from starting to crashed

Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...

2022-07-27T00:20:18.954692+00:00 app[web.1]:     at Module.require (node:internal/modules/cjs/loader:1005:19) {

2022-07-27T00:20:18.954692+00:00 app[web.1]:   diagnosticCodes: [ 2724 ]

2022-07-27T00:20:18.954693+00:00 app[web.1]: }

2022-07-27T00:20:18.969071+00:00 app[web.1]: npm notice 

2022-07-27T00:20:18.969153+00:00 app[web.1]: npm notice New minor version of npm available! 8.11.0 -> 8.15.0

2022-07-27T00:20:18.969300+00:00 app[web.1]: npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.15.0>

2022-07-27T00:20:18.969351+00:00 app[web.1]: npm notice Run `npm install -g npm@8.15.0` to update!

2022-07-27T00:20:18.969493+00:00 app[web.1]: npm notice 

2022-07-27T00:20:19.097712+00:00 heroku[web.1]: Process exited with status 1

2022-07-27T00:20:19.149436+00:00 heroku[web.1]: State changed from starting to crashed

2022-07-27T01:12:07.267778+00:00 heroku[web.1]: State changed from crashed to starting

2022-07-27T01:12:21.820252+00:00 heroku[web.1]: Starting process with command `/bin/sh -c npm\ run\ server`

2022-07-27T01:12:23.640658+00:00 app[web.1]: 

2022-07-27T01:12:23.640671+00:00 app[web.1]: > bot-wa@2.6.9 server

2022-07-27T01:12:23.640672+00:00 app[web.1]: > ts-node --project ./tsconfig.json -r tsconfig-paths/register src/main.ts --server

2022-07-27T01:12:23.640672+00:00 app[web.1]: 

2022-07-27T01:12:29.964415+00:00 app[web.1]: /allen/node_modules/ts-node/src/index.ts:859

2022-07-27T01:12:29.964440+00:00 app[web.1]:     return new TSError(diagnosticText, diagnosticCodes, diagnostics);

2022-07-27T01:12:29.964440+00:00 app[web.1]:            ^

2022-07-27T01:12:29.966464+00:00 app[web.1]: TSError: ⨯ Unable to compile TypeScript:

2022-07-27T01:12:29.966470+00:00 app[web.1]: src/utils/connect.utils.ts(1,59): error TS2724: '"@adiwajshing/baileys"' has no exported member named 'MessageUpdateType'. Did you mean 'MessageUpsertType'?

2022-07-27T01:12:29.966471+00:00 app[web.1]: 

2022-07-27T01:12:29.966471+00:00 app[web.1]:     at createTSError (/allen/node_modules/ts-node/src/index.ts:859:12)

2022-07-27T01:12:29.966472+00:00 app[web.1]:     at reportTSError (/allen/node_modules/ts-node/src/index.ts:863:19)

2022-07-27T01:12:29.966472+00:00 app[web.1]:     at getOutput (/allen/node_modules/ts-node/src/index.ts:1077:36)

2022-07-27T01:12:29.966472+00:00 app[web.1]:     at Object.compile (/allen/node_modules/ts-node/src/index.ts:1433:41)

2022-07-27T01:12:29.966472+00:00 app[web.1]:     at Module.m._compile (/allen/node_modules/ts-node/src/index.ts:1617:30)

2022-07-27T01:12:29.966473+00:00 app[web.1]:     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)

2022-07-27T01:12:29.966474+00:00 app[web.1]:     at Object.require.extensions.<computed> [as .ts] (/allen/node_modules/ts-node/src/index.ts:1621:12)

2022-07-27T01:12:29.966474+00:00 app[web.1]:     at Module.load (node:internal/modules/cjs/loader:981:32)

2022-07-27T01:12:29.966475+00:00 app[web.1]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)

2022-07-27T01:12:29.966475+00:00 app[web.1]:     at Module.require (node:internal/modules/cjs/loader:1005:19) {

2022-07-27T01:12:29.966476+00:00 app[web.1]:   diagnosticCodes: [ 2724 ]

2022-07-27T01:12:29.966476+00:00 app[web.1]: }

2022-07-27T01:12:29.980965+00:00 app[web.1]: npm notice 

2022-07-27T01:12:29.981041+00:00 app[web.1]: npm notice New minor version of npm available! 8.11.0 -> 8.15.0

2022-07-27T01:12:29.981191+00:00 app[web.1]: npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.15.0>

2022-07-27T01:12:29.981235+00:00 app[web.1]: npm notice Run `npm install -g npm@8.15.0` to update!

2022-07-27T01:12:29.981359+00:00 app[web.1]: npm notice 

2022-07-27T01:12:30.111536+00:00 heroku[web.1]: Process exited with status 1

2022-07-27T01:12:30.221335+00:00 heroku[web.1]: State changed from starting to crashed

Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...

2022-07-27T01:12:29.966475+00:00 app[web.1]:     at Module.require (node:internal/modules/cjs/loader:1005:19) {

2022-07-27T01:12:29.966476+00:00 app[web.1]:   diagnosticCodes: [ 2724 ]

2022-07-27T01:12:29.966476+00:00 app[web.1]: }

2022-07-27T01:12:29.980965+00:00 app[web.1]: npm notice 

2022-07-27T01:12:29.981041+00:00 app[web.1]: npm notice New minor version of npm available! 8.11.0 -> 8.15.0

2022-07-27T01:12:29.981191+00:00 app[web.1]: npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.15.0>

2022-07-27T01:12:29.981235+00:00 app[web.1]: npm notice Run `npm install -g npm@8.15.0` to update!

2022-07-27T01:12:29.981359+00:00 app[web.1]: npm notice 

2022-07-27T01:12:30.111536+00:00 heroku[web.1]: Process exited with status 1

2022-07-27T01:12:30.221335+00:00 heroku[web.1]: State changed from starting to crashed

```

**Comment by renatofb** [comment]
Same problem here but reverse,

'"@adiwajshing/baileys"' has no exported member named 'MessageUpsertType'. Did you mean 'MessageUpdateType'?

**Comment by Paiiss** [comment]
I missed an update from Bailey, I didn't have time to check it so I looked for another solution.

Sorry for the delay ^-^
